name: currency
description: "An application to show the currency rate"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  http: ^1.1.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  parameterized_test: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.9
  freezed: ^2.4.6

flutter:
  uses-material-design: true
